pipeline {
  agent { label 'docker' }

  stages {

    stage ('Analyze with SonarQube') {
      steps {
          script {
            def scannerHome = tool 'SonarQubeScanner4'
            withSonarQubeEnv("siotgov") {
              sh "${scannerHome}/bin/sonar-scanner"
            }
          }
          
      }
    }

  }

}